### ISSUE TITLE
Build failed cmake

### ISSUE THREAD

**Issue by WissamCodit** [tony-xlh/react-native-document-scanner#3]
Hey, when I'm trying to build the the app It will show build failed and this error, any help please ?

[CXX1429] error when building with cmake using C:\smartAP\Client\EasyAppMobile\node_modules\react-native-vision-camera\android\CMakeLists.txt: C++ build system [prefab] failed while executing:
    @echo off
    "C:\\Program Files\\Android\\Android Studio\\jbr\\bin\\java" ^
      --class-path ^
      "C:\\Users\\WissamKabaha\\.gradle\\caches\\modules-2\\files-2.1\\com.google.prefab\\cli\\2.0.0\\f2702b5ca13df54e3ca92f29d6b403fb6285d8df\\cli-2.0.0-all.jar" ^
      com.google.prefab.cli.AppKt ^
      --build-system ^
      cmake ^
      --platform ^
      android ^
      --abi ^
      arm64-v8a ^
      --os-version ^
      21 ^
      --stl ^
      c++_shared ^
      --ndk-version ^
      23 ^
      --output ^
      "C:\\Users\\WISSAM~1\\AppData\\Local\\Temp\\agp-prefab-staging6666331456974029935\\staged-cli-output" ^
      "C:\\Users\\WissamKabaha\\.gradle\\caches\\transforms-3\\cc50c91fd5a56d5e31a75f6dcfd345b3\\transformed\\jetified-react-android-0.72.3-debug\\prefab" ^
      "C:\\Users\\WissamKabaha\\.gradle\\caches\\transforms-3\\67fa42c0d40c092460eee86c1e70737f\\transformed\\jetified-fbjni-0.3.0\\prefab" ^
      "C:\\smartAP\\Client\\EasyAppMobile\\node_modules\\react-native-worklets-core\\android\\build\\intermediates\\prefab_package\\debug\\prefab"
  from C:\smartAP\Client\EasyAppMobile\node_modules\react-native-vision-camera\android
Usage: prefab [OPTIONS] PACKAGE_PATH...

Error: Invalid value for "PACKAGE_PATH": Directory "C:\smartAP\Client\EasyAppMobile\node_modules\react-native-worklets-core\android\build\intermediates\prefab_package\debug\prefab" is not readable.

**package json:**
{
  "name": "easyapp_mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.3.2",
    "@microsoft/signalr": "^7.0.12",
    "@react-native-async-storage/async-storage": "^1.19.4",
    "@react-native-community/netinfo": "^11.2.1",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-native-picker/picker": "^2.4.10",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@react-navigation/stack": "^6.3.17",
    "@reduxjs/toolkit": "^1.9.5",
    "axios": "^1.4.0",
    "events": "^3.3.0",
    "i18next": "^23.8.2",
    "lottie-react-native": "^6.4.0",
    "moment-timezone": "^0.5.43",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-hook-form": "^7.48.2",
    "react-i18next": "^14.0.2",
    "react-native": "0.72.3",
    "react-native-animatable": "^1.3.3",
    "react-native-blob-util": "^0.19.1",
    "react-native-calendars": "^1.1302.0",
    "react-native-device-info": "^10.11.0",
    "react-native-document-scanner-plugin": "^0.9.0",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-elements": "^3.4.3",
    "react-native-flash-message": "^0.4.2",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-get-random-values": "^1.10.0",
    "react-native-paper": "^5.11.1",
    "react-native-pdf": "^6.7.1",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "^3.6.1",
    "react-native-restart": "^0.0.27",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.23.0",
    "react-native-select-dropdown": "^3.4.0",
    "react-native-share": "^8.0.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^12.1.1",
    "react-native-table-component": "^1.2.2",
    "react-native-tailwindcss": "^1.1.11",
    "react-native-uuid": "^2.0.1",
    "react-native-vector-icons": "^10.0.0",
    "react-native-vision-camera": "^3.6.17",
    "react-native-worklets-core": "^0.2.4",
    "react-redux": "^8.1.1",
    "react-router-dom": "^6.14.2",
    "react-signalr": "^0.2.18",
    "redux": "^4.2.1",
    "redux-thunk": "^2.4.2",
    "tailwindcss-react-native": "^1.7.10",
    "uuid": "^9.0.1",
    "vision-camera-dynamsoft-document-normalizer": "^1.0.0",
    "yup": "^1.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.9",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "autoprefixer": "^10.4.14",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.7",
    "postcss": "^8.4.27",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "tailwindcss": "^3.3.2",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

**Comment by xulihang** [comment]
This is related to vision camera. You can find related issues in its repo: https://github.com/mrousavy/react-native-vision-camera/issues/1775#issuecomment-1768626180

**Comment by vanso-hubsi** [comment]
@WissamCodit were you able to fix this? I couldn't really find the solution in the vision-camera issue...

**Comment by xulihang** [comment]
Close this as this repo has been updated to use vision camera v4.
