### ISSUE TITLE
Unable to build on Android

### ISSUE THREAD

**Issue by AACKL** [tony-xlh/react-native-document-scanner#4]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.dynamsoft:dynamsoftcapturevisionrouter:2.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftcapturevisionrouter/2.2.10/dynamsoftcapturevisionrouter-2.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer
   > Could not find com.dynamsoft:dynamsoftcore:3.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftcore/3.2.10/dynamsoftcore-3.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer
   > Could not find com.dynamsoft:dynamsoftdocumentnormalizer:2.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftdocumentnormalizer/2.2.10/dynamsoftdocumentnormalizer-2.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer
   > Could not find com.dynamsoft:dynamsoftimageprocessing:2.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftimageprocessing/2.2.10/dynamsoftimageprocessing-2.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer
   > Could not find com.dynamsoft:dynamsoftlicense:3.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftlicense/3.2.10/dynamsoftlicense-3.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer
   > Could not find com.dynamsoft:dynamsoftutility:1.2.10.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - https://repo.maven.apache.org/maven2/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/jsc-android/dist/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - https://dl.google.com/dl/android/maven2/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - https://www.jitpack.io/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/react-native/android/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
       - file:/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/expo-camera/android/maven/com/dynamsoft/dynamsoftutility/1.2.10/dynamsoftutility-1.2.10.pom
     Required by:
         project :app > project :vision-camera-dynamsoft-document-normalizer

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 42s
10 actionable tasks: 2 executed, 8 up-to-date
Error: /Users/xentraemployee/Documents/laragon/www/koin-react/qa/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
Error: /Users/xentraemployee/Documents/laragon/www/koin-react/qa/android/gradlew app:assembleDebug -x lint -x test --configure-on-demand --build-cache -PreactNativeDevServerPort=8081 -PreactNativeArchitectures=arm64-v8a,armeabi-v7a exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/@expo/spawn-async/build/spawnAsync.js:42:23)
    at Object.onceWrapper (node:events:633:26)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1104:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
    ...
    at spawnAsync (/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/@expo/spawn-async/build/spawnAsync.js:7:23)
    at spawnGradleAsync (/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:96:48)
    at assembleAsync (/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:74:18)
    at runAndroidAsync (/Users/xentraemployee/Documents/laragon/www/koin-react/qa/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:45:37)
    
--------------------------------------------------------------------------------------
"react-native": "^0.74.2",
"expo": "~51.0.11",
"vision-camera-dynamsoft-document-normalizer": "^3.2.3",
"react-native-vision-camera": "^4.3.2",
"react-native-worklets-core": "^1.5.0",
--------------------------------------------------------------------------------------
Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 11, 2024
Runtime version: 17.0.10+0-17.0.10b1087.21-11609105 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
--------------------------------------------------------------------------------------
JDK: 17
Gradle Version: 8.8
minSdkVersion: 23
compileSdkVersion: 34
targetSdkVersion: 34

**Comment by xulihang** [comment]
This is related to the dynamsoft's maven repo is not being used.

This should be added automatically since I've had these lines in the plugin: https://github.com/tony-xlh/vision-camera-dynamsoft-document-normalizer/blob/086dcd35448b02dd2d82fa54763de499dc619211/android/build.gradle#L84-L90

If you still have the problem, you can add the maven repo to your project.

**Comment by AACKL** [comment]
@xulihang - it's working now, thank you for pointing me to the right direction
